#!/usr/bin/env php
<?php
require_once(__DIR__ . '/vendor/autoload.php');

use karthus\console\Command;
use function karthus\app_path;

$cli = new Command();
$cli->setName('karthus cli');
$cli->installInternalCommands()
    ->installCommands(app_path() . "/command");

$cli->run();
